### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by krunaldodiya** [coopcycle/react-native-pin-screen#2]
how to install,

when doing npm install --save how to install, says repository not found

**Comment by alexsegura** [comment]
Hello,

The package is not deployed on NPM, you need to install from GitHub

```
npm install --save git+https://git@github.com/coopcycle/react-native-pin-screen.git
```

This should work too: 

```
npm install --save coopcycle/react-native-pin-screen
```

**Comment by krunaldodiya** [comment]
thanks
